uploads = []
generated = []

[[outputs]]
id = "qYMDV8mktr1n4Yp_4pDJS"
uri = "file://%D8%AA%D8%AD%D8%AF%D9%8A-%D8%A7%D9%84%D8%AB%D9%84%D8%A7%D8%AB%D9%8A%D9%86.zip"
type = "unspecified"
title = "تحدي الثلاثين - ملفات المشروع"

[[outputs]]
id = "qWKndvsPEW87KcqDvmC-T"
uri = "file://attached_assets/generated_images/tahadi-logo.png"
type = "image"
title = "لوقو تحدي الثلاثين"
